### ISSUE TITLE
About training with multi-GPUs.

### ISSUE THREAD

**Issue by anonymous530** [a1600012888/YOPO-You-Only-Propagate-Once#6]
Hello. It doesn't use DataParallel in train.py in experiments/CIFAR10/wide34.yopo-5-3. Does it mean this can only use one gpu to run this code?

**Comment by zdhNarsil** [comment]
Hi. We haven't tried multi-gpu experiments yet. But it should be ok if you conduct it with `torch.distributed.launch` or `DataParallel`, which you mentioned.

**Comment by anonymous530** [comment]
> Hi. We haven't tried multi-gpu experiments yet. But it should be ok if you conduct it with `torch.distributed.launch` or `DataParallel`, which you mentioned.

Ok, I'm going to try. Thanks for your reply!

**Comment by a1600012888** [comment]
Hi. 
The official tutorial on distributed data parallel can be seen here https://pytorch.org/tutorials/intermediate/ddp_tutorial.html.

The code comments in https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py is also very useful.
